# Generated by Django 3.1.5 on 2021-04-15 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0003_auto_20210415_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postt',
            new_name='Post',
        ),
    ]
