# Generated by Django 3.1.5 on 2021-04-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20210415_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
