# Generated by Django 3.1.5 on 2021-04-16 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
