# Generated by Django 3.1.5 on 2021-04-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_post_publicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
